name: Auto-merge bot PRs

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    # Allow auto-merging PRs opened by codex[bot], github-actions[bot] or dependabot[bot]
    if: >
      github.event.pull_request.base.ref == 'main' &&
      (
        github.event.pull_request.user.login == 'codex[bot]' ||
        github.event.pull_request.user.login == 'github-actions[bot]' ||
        github.event.pull_request.user.login == 'dependabot[bot]'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
      - name: Log merge
        run: echo "Enabled auto merge for PR #${{ github.event.pull_request.number }}"
